require:
  - rubocop-rake
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Layout/LineLength:
  Max: 150

# DSLs produce long blocks.
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
