language: ruby
cache: bundler
rvm:
  - 2.6
  - 2.7
  - 3.0
gemfile:
  - Gemfile

# Force Travis jobs to use the latest version of Bundler
before_install:
  - yes | gem update --system --force
  - gem install bundler
