name: Unit tests
on:
  push:
    branches: [main, next]
  pull_request:
    branches:  [main, next]
jobs:
  # Ruby unit tests
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3", "3.4"]
    # Use a dedicated Gemfile so Gemfile.lock will be ignored
    # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/dev/gemfiles/ci.gemfile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
